name: Angular CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - './PillsTrackingFrontend/PillsTrackingWeb/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ./PillsTrackingFrontend/PillsTrackingWeb/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('./PillsTrackingFrontend/PillsTrackingWeb/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci
      working-directory: ./PillsTrackingFrontend/PillsTrackingWeb

    - name: Build app
      run: npm run build 
      working-directory: ./PillsTrackingFrontend/PillsTrackingWeb
