name: React Native CI
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-mobile:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Authenticate with Expo
        run: expo login -t ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install
        working-directory: PillsTrackingFrontend/PillsTrackingMobile

      - name: Link project UUID
        run: eas init --id 88a97d2d-3070-4f10-a295-f595ca2d0ab4
        working-directory: PillsTrackingFrontend/PillsTrackingMobile

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build app
        run: eas build --platform android --local --non-interactive
        working-directory: PillsTrackingFrontend/PillsTrackingMobile
